config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # Defines the root path route ("/")
  resources :spirits, only: [:index, :show] do
    resources :orders, only: [:new, :create]
    resources :reviews
  end

  resources :recommendations, only: :index
  resources :experiences, only: :create

  resources :orders, only: [:destroy, :show, :index] do
    collection do
      get :order_recommendation
    end
  end


  get "dashboard", to: "pages#dashboard"
  get "maindashboard", to: "pages#maindashboard"
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :spirit
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @recommendations = policy_scope(Recommendation)

    @user = current_user
    @recommendation = @user.recommendations.first(5)
  end
end

app/views/recommendations/index.html.erb
<%= render "shared/navbar" %>

<div style="padding:65px;">
  <div class="pourtour-reco d-flex flex-column">

    <h3 class="text-center mt-4 mb-5 reco-title " >Voici vos recommendations</h3>


    <div class="spirit-card-grid-reco" style="position: relative">
      <% current_user.recommendations.each do |reco| %>
      <div class="spirit-card" style="position: relative">
      <div class="single-chart" style="z-index: 3; position:absolute; top: 5px; left:5px">
        <svg viewbox="0 0 36 36" class="circular-chart green">
          <path class="circle-bg"
            d="M18 2.0845
              a 15.9155 15.9155 0 0 1 0 31.831
              a 15.9155 15.9155 0 0 1 0 -31.831"
          />=
          <path class="circle"
          <%@environ = rand(-10..1)%>
            stroke-dasharray="<%= @result = reco.percentages.round + @environ %>, 100"
            d="M18 2.0845
              a 15.9155 15.9155 0 0 1 0 31.831
              a 15.9155 15.9155 0 0 1 0 -31.831"
          />
          <text x="18" y="20.35" class="percentage"><%= @result %>%</text>
        </svg>
      </div>
        <img class="mt-2" src="<%=reco.spirit.image_url%>" style='padding-top:20px'>
        <div class="spirit-card-infos" style="height: 120px;">
          <div class="spirit-card-content-reco" >
            <div class="spirit-card-header-reco">
              <h4 class="text-center"><%= reco.spirit.name.truncate(27, separator: ' ') %></h4>
              <p class="text-center"><%= reco.spirit.producer %></p>
            </div>
            <div class="spirit-card-content-percentage" style="padding-bottom:10px">
              <button class="btn-category"><%= reco.spirit.category %></button>
            </div>

          </div>
        </div>
      </div>
      <%end %>
    </div>
    <p class= "text-center">Commandez vos 5 échantillons (12cl) correspondant à vos goûts pour 25€. <br> Les 25€ vous seront remboursés lors de votre prochain achat.</p>
    <div class="d-flex justify-content-center align-items-center btn-reco-position ">
      <p class="btn-blanc-reco" data-bs-toggle="modal" data-bs-target="#exampleModal" href="#">Commandez votre coffret</p>
    </div>
  </div>
</div>


      <%# <%= "Commandez votre coffret", order_recommendation_orders_path(spirits: current_user.recommendations.pluck(:spirit_id)), class:"btn-default" %>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header modal-background">
        <h5 class="modal-title " id="exampleModalLabel">Mon panier</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-between">
          <p style="font-weight: 400"> Coffret Dégustation Deflavour</p>
          <p style="font-weight: 400">25€</p>
        </div>
        <ul class="list-unstyled">
          <% current_user.recommendations.each do |reco| %>
          <li>1 x <%= reco.spirit.name %>; 12cl</li>
          <% end %>
          <li>
            <p></p>
          </li>
          <li>
            <div>
              <input type="checkbox" id="livraison" name="livraison">
              <label for="livraison">Livraison express (uniquement valable au 16 villa Gaudelet)</label>
            </div>
          </li>
        </ul>
      </div>
      <div class="modal-footer ">
        <div class="d-flex justify-content-between">
          <p>Sous-total du panier: 25€<p>
          <%= link_to "Payer", order_recommendation_orders_path(spirits: current_user.recommendations.pluck(:spirit_id)), class:"btn-modal" %>
        </div>
      </div>
    </div>
  </div>
</div>