config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # Defines the root path route ("/")
  resources :spirits, only: [:index, :show] do
    resources :orders, only: [:new, :create]
    resources :reviews
  end

  resources :recommendations, only: :index
  resources :experiences, only: :create

  resources :orders, only: [:destroy, :show, :index] do
    collection do
      get :order_recommendation
    end
  end


  get "dashboard", to: "pages#dashboard"
  get "maindashboard", to: "pages#maindashboard"
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/views/shared/_dashboard_mini.html.erb
<h1 class="text-center my-5" >Profil Aromatique </h1>
<div class="d-flex justify-content-around flex-row-reverse">
  <div class="d-flex flex-column" style="width: 40%;">
    <div class= "m-5">
    <h2>Synthese</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit possimus cum, saepe soluta nobis inventore rem mollitia veritatis, a sunt, sequi natus rerum repellendus quas. Ea temporibus reprehenderit quisquam harum!</p>
    </div>
    <div class= "m-5">
    <h3>Description</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat blanditiis ipsam rerum dolorum! Harum eum nostrum aut atque est error at dolorum in ullam cupiditate ab laboriosam, et, voluptas numquam?</p>
    </div>
  </div>

  <div style="width: 500px; height: 500px;">
    <canvas  id="myChart"></canvas>

  </div>
</div>
<div class="text-center">
  <%=link_to "Recommendation", recommendations_path, class:"btn-default" %>
</div>

app/views/shared/_experience_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= true %>">
  <%= f.input :spirit, class:"experience-label", collection: Spirit.all, input_html: { multiple: true, data: { controller: "tom-select", tom_select_options_value: { tags: true }, nested_form_target:"field" } } %><i data-nested-form-target="tick" class="d-none tick-icon fa-solid fa-check"></i>

  <button type="button" class="experience-button-remove" data-action="nested-form#remove"><i class="fa-solid fa-minus"></i></button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-left">
    <div class="footer-left-text">
      <a class="nav-link" href="">A PROPOS</a>
      <a class="nav-link" href="">NOUS CONTACTER</a>
      <a class="nav-link" href="">DEVENIR AMBASSADEUR</a>
      <a class="nav-link" href="">CARTE CADEAU</a>
      <a class="nav-link"  href="">LIVRAISONS / RETOUR / FAQ</a>
    </div>
    <div class="footer-left-socials">
      <a class="nav-link" href="https://github.com/adrih1/deflavour" target="_blank"><i class="fab fa-github"></i></a>
      <a class="nav-link"  href="" target="_blank"><i class="fab fa-instagram"></i></a>
    </div>
  </div>
  <div class="footer-right">
    <p class="nav-link">Recevez nos actualités</p>
    <div class="email-container">
      <p>Votre adresse email</p>
    </div>


  </div>
</div>

app/views/shared/_login.html.erb
<%= simple_form_for("user", url: user_session_path, data: {turbo: false}) do |f| %>
  <div class="form-inputs">
    <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
    <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>
    <%# <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions d-flex justify-content-center">
    <%= f.button :submit, "Log in", class:"btn-home-login" %>
  </div>
<% end %>

app/views/shared/_modal-reviews.html.erb
<!-- Modal -->
<div class="modal-dialog">
  <div class="modal-content-reviews">
    <div class="modal-body-reviews">

      <h5 class="text-center review-title p-4"><%= spirit.name%></h5>
        <img class="d-flex justify-content-center" src="<%=spirit.image_url%>">
        <%= simple_form_for [spirit, Review.new] do |f| %>
          <div data-controller="slider">
            <div class="d-flex flex-row ">
              <div class="me-2">
                Votre note:
              </div>
              <div class="text-center" data-slider-target="number">
                5
              </div>
            </div>
            <%= f.input :rating, collection: Review::AUTHORIZED_RATINGS, label: false, as: :range, include_blank: false, label_html: { class: 'form-label-review '}, input_html: { class: 'form-range', min:"0", max:"10", "data-action": "input->slider#change", "data-slider-target": "input" } %>
          </div>
          <%= f.input :content, placeholder: 'Décrivez votre experience avec ce spiritueux', label: "Commentaire", label_html: { class: 'form-label-review ' }, input_html: { class: 'form-input-review' } %>
          <div class="review-cache">
            <%= f.submit "Noter", class: "btn btn-modal-reviews", data: { controller: 'alert', action: 'click->alert#hop'} %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_mon_bar.html.erb
<h1 class="mon-bar-main-title">Mon Bar</h1>
<div>
  <div class="pourtour">
  <h2 class="mon-bar-title">En attente de note</h2>
  <div class="spirit-card-grid-dash">
    <% current_user.recommendations.each do |recomendation| %>
      <% unless current_user.reviewed_spirits.include?(recomendation.spirit)%>
      <div class="spirit-card">
        <img src="<%=recomendation.spirit.image_url%>">
        <div class="spirit-card-content-dash">
          <div class="spirit-card-header-dash">
            <div class="spirit-card-dash-title sp-2 text-center">
              <%= recomendation.spirit.name %>
            </div>
              <!-- Button trigger modal -->
              <button type="button" class="btn-default-reviews" data-bs-toggle="modal" data-bs-target="#exampleModal<%=recomendation.id%>">
                Notez ce spiritueux
              </button>
              <div class="modal fade" id="exampleModal<%=recomendation.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <%= render "shared/modal-reviews", spirit:recomendation.spirit %>
              </div>
          </div>
        </div>
      </div>
      <%end %>
    <%end %>
  </div>
  </div>
</div>
<div class="pourtour my-5">
  <h2 class="mon-bar-title"> Mes bouteilles</h2>
  <div class="spirit-card-grid-dash">
    <% (current_user.spirits + current_user.reviewed_spirits).uniq.each do |spirit| %>
      <% if Review.find_by(spirit: spirit, user: current_user) %>
      <div class="spirit-card">
        <img src="<%=spirit.image_url%>">
        <div class="spirit-card-content">
          <div class="spirit-card-header">
            <%= spirit.name %>
          </div>
        </div>
      </div>
      <% end %>
    <%end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-deflavour">
  <div class="navbar-content">
    <ul class="navbar-nav me-auto">
      <div class="navbar-left">
        <li class="nav-item active">
          <%=link_to "Spiritueux", spirits_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Producteurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Concept</a>
        </li>
      </div>
      <div class="navbar-center">
      <li class="nav-item active">
        <%=link_to "DeFlavour", root_path, id:"DeFlavour-name" %>
      </li>

      </div>
      <div class="navbar-right">
        <% if current_user && current_user.experiences.length > 0%>
          <%= link_to "Voir mon profil", maindashboard_path, class: "text-decoration-none nav-link mb-auto mt-auto" %>
        <%end%>
        <li class="nav-item active">
          <a class="nav-link"  href="#"><i  class="nav-link fa-solid fa-magnifying-glass"></i></a>
        </li>
        <% if current_user %>
        <li class="nav-item active">
          <%=link_to "Déconnexion",  destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link"%>
        </li>
        <% else %>
        <li class="nav-item active">
          <a class="nav-link" data-bs-toggle="modal" data-bs-target="#loginModal" href="#">Log In</a>
        </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>




<!-- Modal LOG IN -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
          <div class="form-container">
            <h2 style="color:white">Log in</h2>
            <%= render "shared/login" %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_profil_aromatique.html.erb
<div id="profil" class="d-flex flex-row" style="height: calc(100vh - 64px);">
  <div class="carre-gauche">
    <div class="d-flex justify-content-around">
      <div class="d-flex carre-text flex-column">
        <h1 class="mb-5" >Profil Aromatique - <span><em><%= @user.alcool_profile[:family] %></em></span> </h1>
        <h2 class="mt-2">Synthese</h2>
        <p class="mb-5">Famille : Vous aimez les spiritueux majoritairement <%= @user.alcool_profile[:text1]%>.</p>
        <div class= "description" style= "position: relative;">
          <h3>Description</h3>
          <p>Vous êtes <strong><%= @user.alcool_profile[:accroche] %></strong></p>
          <p class="mb-4"> <%= @user.alcool_profile[:description] %></p>
          <p class="mb-2"><%= @user.alcool_profile[:stars] %></p>
          <div class="d-flex">
            <img class="avatar-big photo1" src="<%= @user.alcool_profile[:photo_one] %>" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="carre-droite">
    <div style="width: 600px; height: 600px; margin: auto;padding-top:5px">
      <canvas  id="myChartd"></canvas>
      <div id="datad" class="d-none">
        <%= @datad  %>
      </div>
      <div id="valued" class="d-none">
        <%= @valued  %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_signup.html.erb
<%= simple_form_for("user", url: user_registration_path, data: {turbo: false}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
  </div>

  <div class="form-actions d-flex justify-content-center">
    <%= f.button :submit, "Sign up", class:"btn-home-login" %>
  </div>
<% end %>

app/views/shared/_spirit-card.html.erb
<div class="spirit-card">
  <img src="https://images.unsplash.com/photo-1651381850425-204da28f1cf8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2846&q=80"/>
  <div class="spirit-card-infos">
    <div class="spirit-card-content">
      <div class="spirit-card-header">
        <h2>Title here</h2>
        <p>4/5 <i id="rating" class="fa-solid fa-star"></i></p>
      </div>
      <p>Short description here!</p>
      <div class="spirit-card-footer">
        <h2 class="card-trip-pricing">£99.99</h2>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="spirit-card-producer avatar-bordered"/>
      </div>
    </div>
  </div>
</div>