config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # Defines the root path route ("/")
  resources :spirits, only: [:index, :show] do
    resources :orders, only: [:new, :create]
    resources :reviews
  end

  resources :recommendations, only: :index
  resources :experiences, only: :create

  resources :orders, only: [:destroy, :show, :index] do
    collection do
      get :order_recommendation
    end
  end


  get "dashboard", to: "pages#dashboard"
  get "maindashboard", to: "pages#maindashboard"
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/views/pages/dashboard.html.erb
<%= render "shared/navbar" %>

<div class="" data-controller='reco-carousel chart'>
  <div class="d-flex" style="height: calc(100vh - 64px);" data-reco-carousel-target='profile'>
    <div class="carre-gauche">
      <div class=" carre-text d-flex flex-column">
        <h1 class="mb-5" >Profil Aromatique - <span><em><%= @choice.dig(:family) %></em></span> </h1>
        <div>
          <h2 class="mt-2">Synthese</h2>
          <p class="mb-5"><%="Famille : Vous aimez les spiritueux majoritairement #{@user.alcool_profile[:text1]}."%></p>
        </div>
        <div class= "description" style= "position: relative;">
          <h3>Description</h3>
          <p>Vous êtes <strong><%= @choice.dig(:accroche) %></strong></p>
          <p class="mb-4"><%= @choice.dig(:description) %></p>
          <p class="mb-4"><%= @choice.dig(:stars) %></p>
        </div>
        <div class="d-flex">
          <img class="avatar-big photo1" src="<%= @choice[:photo_one] %>" />
        </div>

      </div>
    </div>
    <div class="carre-droite">
      <div style="width: 600px; height: 600px; margin: auto;padding-top:5px">
        <canvas  id="myChart"></canvas>
      </div>

    </div>
  </div>

    <div class="text-center btn-position">
      <%=link_to "Recommandations", '#', class:"btn-dash", 'data-reco-carousel-target':'buttonreco', 'data-action':'click->reco-carousel#loading' %>
      <%=link_to "Recommandations", recommendations_path, class:"btn-dash d-none", 'data-reco-carousel-target':'redirect'%>
    </div>

  <%# LOADING SCREEN %>
  <div class="carousel-container d-none" style="height:100vh; display:flex; flex-direction: column; align-items: center; justify-content: center;" data-reco-carousel-target='carousel'>
    <div class="loading-text">Nous cherchons les meilleurs spiritueux pour vous !</div>
    <div class="icon-cards">
      <div class="icon-cards__content">
        <div class="icon-cards__item"><img src="https://static.wixstatic.com/media/356965_98f49cd39c544636b2a8727347ffe9cd~mv2.png/v1/crop/x_27,y_0,w_229,h_283/fill/w_321,h_370,al_c,lg_1,q_85,enc_auto/cognac.png" alt=""></div>
        <div class="icon-cards__item"><img src="https://static.wixstatic.com/media/356965_06f18fcc6d4e4f1b949b45882f72d285~mv2.png/v1/crop/x_27,y_0,w_229,h_283/fill/w_321,h_370,al_c,lg_1,q_85,enc_auto/gin2.png" alt=""></div>
        <div class="icon-cards__item"><img src="https://static.wixstatic.com/media/356965_f8eb6086105d474cac72421087821703~mv2.png/v1/crop/x_27,y_0,w_229,h_283/fill/w_321,h_370,al_c,lg_1,q_85,enc_auto/absinthe.png" alt=""></div>
        <div class="icon-cards__item"><img src="https://static.wixstatic.com/media/356965_ca9079a3a1fd4ac7a0add6de9ee36229~mv2.png/v1/crop/x_28,y_0,w_227,h_283/fill/w_318,h_366,al_c,lg_1,q_85,enc_auto/rhum.png" alt=""></div>
        <div class="icon-cards__item"><img src="https://static.wixstatic.com/media/356965_06f18fcc6d4e4f1b949b45882f72d285~mv2.png/v1/crop/x_27,y_0,w_229,h_283/fill/w_321,h_370,al_c,lg_1,q_85,enc_auto/gin2.png" alt=""></div>
      </div>
    </div>
    <div class="progress"></div>
  </div>



</div>

<div id="data" class="d-none">
  <%= @data  %>
</div>
<div id="value" class="d-none">
  <%= @value  %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <%if user_signed_in? %>
    <div class="banner" data-controller='banner-change loader'>
      <div  class="banner-subcontainer" data-banner-change-target='subcontainer'>
        <%# LOADING ANIMATION HIDDEN %>
        <div  class='d-none'data-loader-target='content' style="width: 100%; height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center;">
          <div class="loading-text" style="color:white; margin-bottom:20px">Creation de votre profil aromatique</div>
          <div class="progress" style="width:25%"></div>
        </div>

        <h1 data-loader-target='title'>Découvrez les spiritueux conçus pour vous.</h1>
        <button class="text-decoration-none btn-home" data-banner-change-target='button' data-action='click->banner-change#newexperience'>Commencer</button>
        <%# FORMULAIRE CACHÉ %>
        <div class="banner experience-form-container scroll-banner" data-banner-change-target='banner' data-loader-target='experiences' style="width:100%">
          <%= simple_form_for :experiences, url: experiences_path, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
            <h1>Quels spiritueux aimez-vous ?</h1>
            <template data-nested-form-target="template">
              <%= f.fields_for :spirits, Experience.new, child_index: 'NEW_RECORD' do |experience_fields| %>
                <%= render "shared/experience_form",f: experience_fields %>
              <% end %>
            </template>

            <%= f.fields_for :spirits do |experience_fields|  %>
              <%= render "shared/experience_form", f: experience_fields %>
            <% end %>

            <!-- Inserted elements will be injected before that target. -->
            <div data-nested-form-target="target"></div>

            <div class="form-footer">
              <button type="button" data-action="nested-form#add"  class="experience-button"><i class="fa-regular fa-plus"> Ajouter</i></button>
            </div>
            <%# Fake Button just to launch loader %>
            <div style="width:100%; display:flex; justify-content:center;"><p class="launch-experience" data-action='click->loader#loading'>Générer mon profil aromatique</p></div>
            <%# Real button submit hidden but clicked after loading time with js controller %>
            <div style="width:100%; display:flex; justify-content:center;"><%= f.submit 'GÉNÉRÉR MON PROFIL AROMATIQUE', class:"d-none", 'data-loader-target':'submit' %></div>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
      <div style="height: 350px;" class="d-flex flex-column text-center justify-content-center">
        <div>
          <h1>TROUVE LE SPIRITUEUX FAIT POUR TOI</h1>
        </div>
        <div class= "sous-titre">
          <p>Liquors recomendations just for you</p>
        </div>
        <%= link_to "Créer ton profile aromatique", dashboard_path, class: "text-decoration-none btn-home" %>
      </div>
    </div>
  <% end %>
</div>


<%= render "shared/navbar" %>

    <div class="big-cards">
      <div class="cards">
        <%= link_to spirits_path(category: "whisky"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1655786300011-fd83fb824a75?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80)">
          WHISKY
        </div>
        <% end %>

        <%= link_to spirits_path(category: "mezcal"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1639705529453-18e337dbfa2b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80)">
          MEZCAL
        </div>
        <% end %>

        <%= link_to spirits_path(category: "vodka"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1650261064514-eaeb5a296434?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2960&q=80)">
          VODKA
        </div>
        <% end %>

        <%= link_to spirits_path(category: "rhum"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1586315776885-a176ffccbe01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80)">
          RHUM
        </div>
        <% end %>


        <%= link_to spirits_path(category: "armagnac"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1504279577054-acfeccf8fc52?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80)">
          ARMAGNAC
        </div>
        <% end %>

        <%= link_to spirits_path(category: "gin"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1584353781226-579f0ab7c770?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1773&q=80)">
          GIN
        </div>
        <% end %>

        <%= link_to spirits_path(category: "tequila"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1654898628126-3c19d3133c5d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80)">
          TEQUILA
        </div>
        <% end %>

        <%= link_to spirits_path(category: "cognac"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1596398267243-3e9b68ea5ad9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80)">
          COGNAC
        </div>
        <% end %>

        <%= link_to spirits_path(category: "bourbon"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1444853431252-85562925947d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80)">
          BOURBON
        </div>
        <% end %>

        <%= link_to spirits_path(category: "calvados"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1541600321016-ac52d598f563?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80)">
          CALVADOS
        </div>
        <% end %>

        <%= link_to spirits_path(category: "eau de vie"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1537811465496-6c38a51d2d81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80)">
          EAU DE VIE
        </div>
        <% end %>

        <%= link_to spirits_path(category: "grappa"), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1472352327492-9765783b74e1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80)">
          GRAPPA
        </div>
        <% end %>
      </div>
    </div>
</div>

app/views/pages/maindashboard.html.erb
<%= render "shared/navbar" %>


<div data-controller="chart-bis navlink">
  <div class="d-flex flex-row" data-controller="tabs">
    <ul class="list p-4">
      <li class="nav-link-active" data-action="click->navlink#aromatique" data-navlink-target="aromatique" >
        <p data-action="click->tabs#aromatique" >Profil Aromatique</p>
      </li>
      <li class="nav-link" data-action="click->navlink#alcool" data-navlink-target="alcool">
        <p data-action="click->tabs#alcool" >Profil par Alcool</p>
      </li>
      <li class="nav-link" data-action="click->navlink#bar" data-navlink-target="bar">
        <p data-action="click->tabs#bar" >Mon bar</p>
      </li>
    </ul>

    <div style = "width:100%;">

      <div data-tabs-target="aromatique" >
        <%= render "/shared/profil_aromatique" %>
      </div>

      <div class="hidden-tab" data-tabs-target="alcool">
        <%= render "/shared/profil_par_alcool" %>
      </div>

      <div class="d-none mon-bar" data-tabs-target="bar">
         <%= render "/shared/mon_bar" %>
      </div>

    </div>

  </div>
</div>